### ISSUE TITLE
Fix Pull Request Builder or ensure it's active and working

### ISSUE THREAD

**Issue by takecare** [novoda/accessibilitools#13]
Any disadvantages on adding a PRB on this repo?

**Comment by ataulm** [comment]
There is one but hasn't been run in 2 weeks, pretty sure we had a PR after that so something is incorrect.

https://ci.novoda.com/view/PRB/job/accessibilitools-prb/

**Comment by takecare** [comment]
yeah that's why i closed, it did run in the end 😄

**Comment by ataulm** [comment]
oh :D
