### ISSUE TITLE
Deprecate Action-related classes after verifying whether they are now redundant

### ISSUE THREAD

**Issue by ataulm** [novoda/accessibilitools#29]
#28 added an alternative way to specify custom actions. This should be tested by creating a local release of accessibilitools and determining whether the change causes any issues in any current usage of the project.

If it's fine, then we can deprecate these classes:

- `Action`
- `Actions`
- `ActionsAlertDialogCreator`
- `ActionsAccessibilityDelegate`

when this issue is complete, a new issue should be defined and linked here to delete/remove those classes (probably prior to shipping 2.0 but can be discussed).

**Comment by ataulm** [comment]
There could be a case for keeping the ability to specify actions at runtime: if a paragraph of text is rendered with multiple clickable spans (hyperlinks), then an appropriate pattern is to present these links in a list dialog when clicking on the textview.

However we could still simplify runtime generation of an alertdialog by creating it from the actions in a view's accessibility node info.

**Comment by ataulm** [comment]
Google's added a new API to add accessibility actions to a View using `ViewCompat` in androidx.appcompat-1.1.0.

Seems like very little boiler plate compared to either the old-style Action-related classes, and even the new-style (:sob:) Menu-action related classes.

For this reason, I think we should ditch them (for 2.0).

One thing that is still useful is the `ActionsAlertDialogCreator` or `ActionsMenuAlertDialog`. These create an `AlertDialog` with the actions that are available in a given View. This can be displayed when the user clicks on a View, meaning we can avoid showing actions until the user has registered interest in the View (speeding up what can otherwise be pretty slow navigation).

We can create such an AlertDialog based on the AccessibilityActions that have been set on a View.

TODO:

- create a utility to create an AlertDialog, passing just the View (it'll populate the AlertDialog based on accessibility actions which have been set with the new ViewCompat API).
- delete the older classes
- convert to Kotlin (started this but thought it'd be easier if we ditched a bunch of classes first)
- release 2.0

**Comment by ataulm** [comment]
Will PR this after AppCompat hits stable https://github.com/novoda/accessibilitools/compare/master...task/add-accessibility-actions-alert-dialog?expand=1

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
